import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                       profile
                                   }: Readonly<{
    children: React.ReactNode;
    profile: React.ReactNode
}>) {
    const isAdmin = false
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <nav>
            <ul className='flex gap-10 justify-center p-1 bg-amber-300 items-center font-bold text-blue-800'>
                <li>
                    <Link href='/products'>
                        Products
                    </Link>
                </li>
                <li>
                    <Link href='/about'>
                        About
                    </Link>
                </li>
            </ul>
        </nav>
        {children}
        {isAdmin && profile}
        </body>
        </html>
    );
}
